name: reviews_dashboard
description: A realtime dashboard for user reviews.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  freezed_annotation:
  flutter_riverpod:
  flutter_rating_bar:
  flutter_map:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
