name: pull_request_ci
on: pull_request
jobs:
  lint-unit-tests:
    name: Lint + Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Generate fake firebase options
        run: |
          echo "import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

          class DefaultFirebaseOptions {
            static FirebaseOptions get currentPlatform {
              return const FirebaseOptions(
                apiKey: '',
                appId: '',
                messagingSenderId: '',
                projectId: '',
                authDomain: '',
                storageBucket: '',
              );
            }
          }" >> lib/firebase_options.dart
      - name: Install packages
        run: flutter pub get
      - name: Lint
        run: flutter analyze
      - name: Tests
        run: flutter test
